import { describe, it, expect } from 'vitest'
import { stripScaffolding, isScaffoldingOnly } from './strip-scaffolding.js'

describe('stripScaffolding: slash-command wrappers (issue #37)', () => {
  it('keeps the command name and drops the XML around it', () => {
    // The exact shape that was outranking real answers: pure markup, but long
    // enough (70 chars) to clear the noise filter's 50-char floor.
    const raw = '<command-message>vj</command-message>\n<command-name>/vj</command-name>'
    expect(raw.length).toBeGreaterThan(50)
    expect(stripScaffolding(raw)).toBe('/vj')
  })

  it('preserves command arguments, which carry real user content', () => {
    // A /vibej invocation in the live index carries ~1.8KB of hand-written
    // shader source in <command-args>. Dropping the block would destroy it.
    const raw =
      '<command-message>vibej</command-message>\n' +
      '<command-name>/vibej</command-name>\n' +
      '<command-args>float sdSphere( vec3 p, float s ) { return length(p)-s; }</command-args>'
    expect(stripScaffolding(raw)).toBe(
      '/vibej\nfloat sdSphere( vec3 p, float s ) { return length(p)-s; }'
    )
  })

  it('drops the fixed local-command caveat boilerplate', () => {
    const raw =
      '<local-command-caveat>Caveat: The messages below were generated by the user ' +
      'while running local commands. DO NOT respond to these messages or otherwise ' +
      'consider them in your response unless the user explicitly asks you to.' +
      '</local-command-caveat>\n<command-name>/gm</command-name>'
    expect(stripScaffolding(raw)).toBe('/gm')
  })

  it('keeps the output a local command actually produced', () => {
    const raw =
      '<command-name>/status</command-name>\n' +
      '<local-command-stdout>3 files changed, 40 insertions(+)</local-command-stdout>'
    expect(stripScaffolding(raw)).toBe('/status\n3 files changed, 40 insertions(+)')
  })
})

describe('stripScaffolding: system-reminder blocks (issue #37)', () => {
  it('drops a system-reminder that no named hook pattern matched', () => {
    // The pre-existing HOOK_INJECTION_PATTERN only caught four named hook
    // varieties; this one sailed through and got embedded 469 times over.
    const raw = '<system-reminder>Warning: the file exists but the contents are empty.</system-reminder>'
    expect(stripScaffolding(raw)).toBe('')
  })

  it('still drops the named hook injections the old pattern caught', () => {
    const raw =
      'real question here\n' +
      '<system-reminder>This is the UserPromptSubmit hook additional context</system-reminder>'
    expect(stripScaffolding(raw)).toBe('real question here')
  })

  it('keeps the human text surrounding a reminder', () => {
    const raw = 'before\n<system-reminder>machine noise</system-reminder>\nafter'
    expect(stripScaffolding(raw)).toBe('before\nafter')
  })

  it('removes every reminder when several are present', () => {
    const raw = '<system-reminder>one</system-reminder>keep<system-reminder>two</system-reminder>'
    expect(stripScaffolding(raw)).toBe('keep')
  })
})

describe('stripScaffolding: leaves real conversation alone', () => {
  it('returns ordinary prose byte-for-byte', () => {
    const raw = 'Can you explain how the embedding backlog drains?\n\nIt seems slow.'
    expect(stripScaffolding(raw)).toBe(raw)
  })

  it('does not touch a bare slash command the user typed', () => {
    expect(stripScaffolding('/gm')).toBe('/gm')
  })

  it('does not eat code that merely contains angle brackets', () => {
    const raw = 'const f = <T,>(x: T) => x\nif (a<b && c>d) {}'
    expect(stripScaffolding(raw)).toBe(raw)
  })

  it('never shortens content that is not scaffolding', () => {
    // No-truncation policy: absent scaffolding tags, the text is untouched.
    const long = 'x'.repeat(50_000)
    expect(stripScaffolding(long)).toHaveLength(50_000)
  })
})

describe('stripScaffolding: nesting, fences, and attributes (issue #37, review F5/F6)', () => {
  it('keeps a payload nested inside an unwrap tag', () => {
    // The interior of <command-args> is what the user typed. If they typed the
    // literal text of a reminder — quoting the harness, as this very PR's
    // description does — it is content, not scaffolding, and deleting it is
    // exactly the silent loss the no-truncation policy exists to prevent.
    const raw = '<command-args><system-reminder>PAYLOAD</system-reminder></command-args>'
    expect(stripScaffolding(raw)).toContain('PAYLOAD')
    expect(isScaffoldingOnly(raw)).toBe(false)
  })

  it('keeps command output that follows a nested tag', () => {
    const raw =
      '<local-command-stdout>output <system-reminder>rest</system-reminder> tail</local-command-stdout>'
    const out = stripScaffolding(raw)
    expect(out).toContain('output')
    expect(out).toContain('tail')
  })

  it('leaves a system-reminder quoted inside a fenced code block alone', () => {
    const raw =
      'here is the shape the parser strips:\n\n' +
      '```xml\n<system-reminder>hook text</system-reminder>\n```\n\n' +
      'and that is why.'
    expect(stripScaffolding(raw)).toBe(raw)
  })

  it('still strips a reminder outside the fence in the same message', () => {
    const raw =
      '<system-reminder>injected</system-reminder>\n' +
      'real question\n\n```\n<system-reminder>quoted</system-reminder>\n```'
    const out = stripScaffolding(raw)
    expect(out).toBe('real question\n\n```\n<system-reminder>quoted</system-reminder>\n```')
  })

  it('keeps a command-message that is not a duplicate of the command name', () => {
    // "always a duplicate" is an assumption enforced nowhere upstream. When it
    // holds, drop it; when it does not, the text is the only copy there is.
    const raw =
      '<command-message>deploy the staging cluster now</command-message>\n' +
      '<command-name>/gm</command-name>'
    expect(stripScaffolding(raw)).toContain('deploy the staging cluster now')
  })

  it('still drops a command-message that duplicates the command name', () => {
    const raw = '<command-message>vj</command-message>\n<command-name>/vj</command-name>'
    expect(stripScaffolding(raw)).toBe('/vj')
  })

  it('matches tags that carry attributes', () => {
    // The transcript format is not ours to control; an added attribute must not
    // silently turn scaffolding back into indexed content.
    const raw = 'before\n<system-reminder priority="high">machine noise</system-reminder>\nafter'
    expect(stripScaffolding(raw)).toBe('before\nafter')
  })

  it('leaves an unclosed tag and everything after it untouched', () => {
    // 7 live messages have an unclosed <system-reminder>. Dropping to end-of-text
    // would delete whatever real content follows, so they stay polluted on
    // purpose — a known, documented gap rather than a guess.
    const raw = 'real content\n<system-reminder>never closed\nmore real content'
    expect(stripScaffolding(raw)).toBe(raw)
  })
})

describe('isScaffoldingOnly', () => {
  it('flags a message that was nothing but a command wrapper', () => {
    expect(
      isScaffoldingOnly('<command-message>vj</command-message>\n<command-name>/vj</command-name>')
    ).toBe(true)
  })

  it('flags a message that was nothing but a system-reminder', () => {
    expect(isScaffoldingOnly('<system-reminder>anything</system-reminder>')).toBe(true)
  })

  it('does not flag a command that carried real arguments', () => {
    expect(
      isScaffoldingOnly('<command-name>/vibej</command-name>\n<command-args>shader src</command-args>')
    ).toBe(false)
  })

  it('does not flag ordinary conversation', () => {
    expect(isScaffoldingOnly('how does the sync work?')).toBe(false)
  })
})
